# Copyright (c) 2023 Graphcore Ltd. All rights reserved.

[book]
title = "TRAMWAY Developer Guide"
authors = ["Silicon Architecture Team"]
description = "Tramway is Rust Async Modelling for hardWare Architecture and sYstems (TRAMWAY)"
src = "md_src"
language = "en"

[preprocessor.alerts]
after = [ "links" ]
renderers = ["html", "linkcheck"]

[preprocessor.cmdrun]

[preprocessor.keeper]
command = "mdbook-keeper"
manifest_dir = "../"
is_workspace = true
externs = [
    "async_trait",
    "tramway_components",
    "tramway_engine",
    "tramway_model_builder",
    "tramway_resources",
    "tramway_track",
]

[output.html]
smart-punctuation = true
additional-css = ["theme/custom.css"]
git-repository-url = "https://github.com/graphcore-research/tramway"
edit-url-template = "https://github.com/graphcore-research/tramway/edit/main/tramway-developer-guide/{path}"

[output.html.playground]
editable = false

[output.html.search]
use-boolean-and = true

[output.linkcheck]
traverse-parent-directories = false
