# Copyright (c) 2023 Graphcore Ltd. All rights reserved.

[package]
name = "tramway-developer-guide"
version = "0.2.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "User guide book source and build system"
documentation.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
strip-ansi-escapes = "0.2.1"
