# Copyright (c) 2025 Graphcore Ltd. All rights reserved.

[changelog]
header = """
<!-- Copyright (c) 2025 Graphcore Ltd. All rights reserved. -->

# Changelog

All notable changes for each release of this package will be documented in this file.
"""
commit_parsers = [
    { message = "^feat", group = "Features" },
    { message = "^fix", group = "Bug Fixes" },
    { message = "^docs", group = "Documentation" },
    { message = "^perf", group = "Performance" },
    { message = "^refactor", group = "Refactor" },
    { message = "^style", group = "Styling" },
    { message = "^test", group = "Testing" },
    { message = "^infra", group = "Infrastructure" },
    { message = "^misc", group = "Miscellaneous Tasks" },
    { body = ".*security", group = "Security" },
    { message = "^chore", skip = true },
]

[workspace]
publish_all_features = true

[[package]]
name = "check-copyright"
changelog_update = false
publish = false

[[package]]
name = "flaky-component"
changelog_update = false
publish = false

[[package]]
name = "flaky-with-delay"
changelog_update = false
publish = false

[[package]]
name = "scrambler"
changelog_update = false
publish = false

[[package]]
name = "sim-fabric"
changelog_update = false
publish = false

[[package]]
name = "sim-pipe"
changelog_update = false
publish = false

[[package]]
name = "sim-ring"
changelog_update = false
publish = false

[[package]]
name = "gwr-developer-guide"
changelog_update = false
publish = false
