# Copyright (c) 2025 Graphcore Ltd. All rights reserved.

[package]
name = "sim-ring"
version = "7.0.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Example simulation of a ring of nodes"
documentation.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["example", "gwr"]
categories = ["asynchronous", "command-line-utilities", "simulation"]
publish.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap.workspace = true
gwr-components = { path = "../../gwr-components", version = "0.7.0" }
gwr-engine = { path = "../../gwr-engine", version = "0.9.0" }
gwr-model-builder = { path = "../../gwr-model-builder", version = "0.2.0" }
gwr-models = { path = "../../gwr-models", version = "0.12.0" }
gwr-track = { path = "../../gwr-track", features = ["perfetto"], version = "0.7.0" }
indicatif.workspace = true
log.workspace = true
