# Copyright (c) 2023 Graphcore Ltd. All rights reserved.

[package]
name = "scrambler"
version = "2.0.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Example component to show how a vector of subcomponents can be registered"
documentation.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["example", "tramway"]
categories = ["asynchronous", "command-line-utilities", "simulation"]
publish.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait.workspace = true
clap.workspace = true
tramway-components = { path = "../../tramway-components" }
tramway-engine = { path = "../../tramway-engine" }
tramway-model-builder = { path = "../../tramway-model-builder" }
tramway-track = { path = "../../tramway-track" }
