# Copyright (c) 2023 Graphcore Ltd. All rights reserved.

[package]
name = "flaky-with-delay"
version = "4.0.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Example component which delays data and randomly drops some of it"
documentation.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["example", "gwr"]
categories = ["asynchronous", "command-line-utilities", "simulation"]
publish.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait.workspace = true
clap.workspace = true
gwr-components = { path = "../../gwr-components", version = "0.7.0" }
gwr-engine = { path = "../../gwr-engine", version = "0.9.0" }
gwr-model-builder = { path = "../../gwr-model-builder", version = "0.2.0" }
gwr-track = { path = "../../gwr-track", version = "0.7.0" }
rand.workspace = true
