# Copyright (c) 2023 Graphcore Ltd. All rights reserved.

[package]
name = "tramway-docpp"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Procedural Macros for Document Preprocessing"
documentation.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["documentation", "tramway"]
categories = ["development-tools", "text-processing"]
publish.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true
path = "src/lib.rs"

[dependencies]
tramway-doc-builder = { path = "../tramway-doc-builder" }
proc-macro2.workspace = true
syn.workspace = true
quote.workspace = true
tempfile.workspace = true

[features]
default = []
asciidoctor = []
typst = []
