[package]
name = "steam-track"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Trace system used by the STEAM simulation engine and models"
documentation.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
capnp.workspace = true
clap.workspace = true
figment.workspace = true
itertools.workspace = true
lazy_static = "1.4.0"
log.workspace = true
num-derive.workspace = true
num-traits.workspace = true
regex.workspace = true
serde.workspace = true
simplelog = "0.12.1"
steam-config = { path = "../steam-config" }

[build-dependencies]
capnpc.workspace = true
walkdir = "2.4.0"

[dev-dependencies]
serial_test = "3.2.0"
