# Copyright (c) 2023 Graphcore Ltd. All rights reserved.

[book]
title = "GWR Developer Guide"
authors = ["Silicon Architecture Team"]
description = "The Great Western Runtime (GWR)"
src = "md_src"
language = "en"

[preprocessor.alerts]
after = [ "links" ]
renderers = ["html", "linkcheck"]

[preprocessor.cmdrun]

[preprocessor.keeper]
command = "mdbook-keeper"
manifest_dir = "../"
is_workspace = true
externs = [
    "async_trait",
    "gwr_components",
    "gwr_engine",
    "gwr_model_builder",
    "gwr_resources",
    "gwr_track",
]

[output.html]
smart-punctuation = true
additional-css = ["theme/custom.css"]
git-repository-url = "https://github.com/graphcore-research/gwr"
edit-url-template = "https://github.com/graphcore-research/gwr/edit/main/gwr-developer-guide/{path}"

[output.html.playground]
editable = false

[output.html.search]
use-boolean-and = true

[output.linkcheck]
traverse-parent-directories = false
