# Copyright (c) 2025 Graphcore Ltd. All rights reserved.

name: CI

on:
  push:
    branches-ignore:
      - "pr/**"
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  warm-build-deps-cache:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-build-dependencies

  warm-dev-deps-cache:
    runs-on: ubuntu-latest
    needs: warm-build-deps-cache

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-dev-dependencies

  lint:
    runs-on: ubuntu-latest
    needs: [warm-build-deps-cache, warm-dev-deps-cache]
    env:
      RUSTFLAGS: -D warnings

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-build-dependencies
      - uses: ./.github/actions/install-dev-dependencies

      - name: Lint with pre-commit
        run: pre-commit run --all-files

  check-semantic-versioning:
    runs-on: ubuntu-latest
    needs: [warm-build-deps-cache, warm-dev-deps-cache]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to cause the main branch to also be fetched
      - uses: ./.github/actions/install-build-dependencies
      - uses: ./.github/actions/install-dev-dependencies
      - uses: ./.github/actions/run-build-command
        with:
          command: pre-commit run --hook-stage manual --all-files cargo-semver-checks
          cache-name: semver
          paths: |
            target/semver-checks/

  build:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    needs: warm-build-deps-cache
    env:
      RUSTFLAGS: -D warnings

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-build-dependencies
      - uses: ./.github/actions/run-build-command
        with:
          command: cargo build --all-features --verbose
          cache-name: ${{ github.job }}

  test:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    needs: warm-build-deps-cache
    env:
      RUSTFLAGS: -D warnings

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-build-dependencies
      - uses: ./.github/actions/run-build-command
        with:
          command: cargo test --all-features --verbose
          cache-name: ${{ github.job }}
          paths: |
            target/
            tramway-developer-guide/doctest_cache/
            tramway-developer-guide/rustdoc_cache/

  benchmark:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    needs: warm-build-deps-cache
    env:
      RUSTFLAGS: -D warnings

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-build-dependencies
      - uses: ./.github/actions/run-build-command
        with:
          command: cargo bench --all-features --verbose
          cache-name: ${{ github.job }}
