# Copyright (c) 2025 Graphcore Ltd. All rights reserved.

name: CI

on:
  push:
    branches-ignore:
      - 'pr/**'
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-build-dependencies
      - uses: ./.github/actions/install-dev-dependencies

      - name: Lint with pre-commit
        run: pre-commit run --all-files

  build_and_test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      CACHED_BUILD_PATHS: |
        target/
        steam-developer-guide/doctest_cache/
        steam-developer-guide/rustdoc_cache/

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-build-dependencies

      - name: Generate cached build key
        run: echo "CACHED_BUILD_KEY=${{ runner.os }}-cargo-steam-${{ hashFiles('**/Cargo.lock') }}" >> $GITHUB_ENV

      - name: Restore cached build files
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.CACHED_BUILD_PATHS }}
          key: ${{ env.CACHED_BUILD_KEY }}

      - name: Build
        run: cargo build --all-features --verbose

      - name: Run tests
        run: cargo test --all-features --verbose

      - name: Run benchmarks
        run: cargo bench --all-features --verbose

      - name: Save build files to cache
        if: github.ref == 'refs/heads/main'
        uses: actions/cache/save@v4
        with:
          path: ${{ env.CACHED_BUILD_PATHS }}
          key: ${{ env.CACHED_BUILD_KEY }}
