# Copyright (c) 2025 Graphcore Ltd. All rights reserved.

name: CI

on:
  push:
    branches-ignore:
      - 'pr/**'
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-build-dependencies
      - uses: ./.github/actions/install-dev-dependencies

      - name: Lint with pre-commit
        run: pre-commit run --all-files

  check-semantic-versioning:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required to cause the main branch to also be fetched
      - uses: ./.github/actions/install-build-dependencies
      - uses: ./.github/actions/install-dev-dependencies

      - name: Get cache access variables
        id: cache-vars
        uses: ./.github/actions/cached-semver-access

      - name: Restore cached build files
        uses: actions/cache/restore@v4
        with:
          path: ${{ steps.cache-vars.outputs.paths }}
          key: ${{ steps.cache-vars.outputs.key }}

      - name: Run cargo semver-checks
        run: pre-commit run --hook-stage manual --all-files cargo-semver-checks

      - name: Save build files to cache
        if: github.ref == 'refs/heads/main'
        uses: actions/cache/save@v4
        with:
          path: ${{ steps.cache-vars.outputs.paths }}
          key: ${{ steps.cache-vars.outputs.key }}

  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      RUSTFLAGS: -D warnings

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-build-dependencies

      - name: Get cache access variables
        id: cache-vars
        uses: ./.github/actions/cached-build-access

      - name: Restore cached build files
        uses: actions/cache/restore@v4
        with:
          path: ${{ steps.cache-vars.outputs.paths }}
          key: ${{ steps.cache-vars.outputs.key }}

      - name: Build
        run: cargo build --all-features --verbose

      - name: Run tests
        run: cargo test --all-features --verbose

      - name: Run benchmarks
        run: cargo bench --all-features --verbose

      - name: Save build files to cache
        if: github.ref == 'refs/heads/main'
        uses: actions/cache/save@v4
        with:
          path: ${{ steps.cache-vars.outputs.paths }}
          key: ${{ steps.cache-vars.outputs.key }}
